In [134]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [135]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [136]:
tokenizer.fit_on_texts(docs)

In [137]:
len(tokenizer.word_index)

17

In [138]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [139]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]])

In [140]:
from keras.models import Sequential
from keras.layers import Embedding
model = Sequential()
model.add(Embedding(18,output_dim=2,input_length=5))

model.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_16 (Embedding)    (None, 5, 2)              36        
                                                                 
Total params: 36 (144.00 Byte)
Trainable params: 36 (144.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [141]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [142]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 34ms/step
[[[-0.03594303 -0.00098633]
  [ 0.02374761 -0.03208984]
  [ 0.03715226  0.02700952]
  [ 0.03715226  0.02700952]
  [ 0.03715226  0.02700952]]

 [[ 0.02374761 -0.03208984]
  [ 0.02374761 -0.03208984]
  [ 0.03715226  0.02700952]
  [ 0.03715226  0.02700952]
  [ 0.03715226  0.02700952]]

 [[-0.04861679  0.00767868]
  [-0.04861679  0.00767868]
  [-0.02501873 -0.01232269]
  [ 0.03715226  0.02700952]
  [ 0.03715226  0.02700952]]

 [[ 0.02543957 -0.0302109 ]
  [-0.01553738  0.0406327 ]
  [ 0.02543957 -0.0302109 ]
  [ 0.02374761 -0.03208984]
  [ 0.02543957 -0.0302109 ]]

 [[-0.03307714  0.03936255]
  [-0.02565287 -0.03450803]
  [-0.02135127 -0.03150751]
  [ 0.00673205  0.01539384]
  [ 0.03715226  0.02700952]]

 [[ 0.00919504 -0.04708469]
  [ 0.00919504 -0.04708469]
  [ 0.03715226  0.02700952]
  [ 0.03715226  0.02700952]
  [ 0.03715226  0.02700952]]

 [[-0.00773983  0.02821039]
  [-0.00773983  0.02821039]
  [ 0.03715226  0.02700952]
  [ 0.037152

In [143]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [144]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [145]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [146]:
X_train.shape

(25000, 50)

In [147]:
model = Sequential()
model.add(Embedding(input_dim=16000, output_dim=2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_17 (Embedding)    (None, 50, 2)             32000     
                                                                 
 simple_rnn_6 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_6 (Dense)             (None, 1)                 33        
                                                                 
Total params: 33153 (129.50 KB)
Trainable params: 33153 (129.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [148]:
import numpy as np
print("Max value in X_train:", np.max(X_train))
print("Max value in X_test:", np.max(X_test))

# Automatically set input_dim for Embedding if needed
max_token_index = max(np.max(X_train), np.max(X_test))
if max_token_index >= 10000:
    print(f"⚠️ WARNING: Found token index {max_token_index} >= 10000. You should increase input_dim in Embedding layer.")
    # Optionally clip instead of changing model
    X_train = np.clip(X_train, 0, 9999)
    X_test = np.clip(X_test, 0, 9999)

Max value in X_train: 88585
Max value in X_test: 88582
⚠️ WARNING: Found token index 88585 >= 10000. You should increase input_dim in Embedding layer.


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10)

Epoch 1/10
782/782 [==============================] - 8s 8ms/step - loss: 0.6464 - accuracy: 0.5924 - val_loss: 0.5191 - val_accuracy: 0.7528
Epoch 2/10
782/782 [==============================] - 6s 8ms/step - loss: 0.4145 - accuracy: 0.8135 - val_loss: 0.4249 - val_accuracy: 0.8060
Epoch 3/10
782/782 [==============================] - 6s 8ms/step - loss: 0.3339 - accuracy: 0.8621 - val_loss: 0.4355 - val_accuracy: 0.8063
Epoch 4/10
782/782 [==============================] - 6s 8ms/step - loss: 0.2879 - accuracy: 0.8839 - val_loss: 0.4584 - val_accuracy: 0.8028
Epoch 5/10
782/782 [==============================] - 6s 8ms/step - loss: 0.2528 - accuracy: 0.9016 - val_loss: 0.4753 - val_accuracy: 0.7977
Epoch 6/10
782/782 [==============================] - 6s 8ms/step - loss: 0.2233 - accuracy: 0.9168 - val_loss: 0.4940 - val_accuracy: 0.7936
Epoch 7/10
782/782 [==============================] - 6s 8ms/step - loss: 0.1975 - accuracy: 0.9268 - val_loss: 0.5387 - val_accuracy: 0.7894
Epoch 